import Request from '../Request'
import paramKeys from '../paramKeys'

export default class UpdateProductRequest extends Request {
  static Keys = {
    PRODUCT_DETAIL_ID: paramKeys.PRODUCT_DETAIL_ID,
    PRODUCT_CODE: paramKeys.PRODUCT_CODE,
    PRODUCT_NAME: paramKeys.PRODUCT_NAME,
    SUPPLIER_ID: paramKeys.SUPPLIER_ID,
    PRODUCT_GROUP_ID: paramKeys.PRODUCT_GROUP_ID,
    DESCRIPTION: paramKeys.DESCRIPTION,
    NOTE: paramKeys.NOTE,
    SPECIFICATIONS: paramKeys.SPECIFICATIONS,
    SURFACE_TYPE: paramKeys.SURFACE_TYPE,
    SURFACE_QUANTIFICATION: paramKeys.SURFACE_QUANTIFICATION,
    SURFACE_THICKNESS: paramKeys.SURFACE_THICKNESS,
    ADHESIVE_TYPE: paramKeys.ADHESIVE_TYPE,
    ADHESIVE_MEASUREMENT: paramKeys.ADHESIVE_MEASUREMENT,
    ADHESIVE_THICKNESS: paramKeys.ADHESIVE_THICKNESS,
    BASE_TYPE: paramKeys.BASE_TYPE,
    BASE_MEASUREMENT: paramKeys.BASE_MEASUREMENT,
    BASE_THICKNESS: paramKeys.BASE_THICKNESS,
    ADHESIVE_FORCE: paramKeys.ADHESIVE_FORCE,
    TEMPERATURE_FROM: paramKeys.TEMPERATURE_FROM,
    TEMPERATURE_TO: paramKeys.TEMPERATURE_TO,
    EXPIRY_YEAR: paramKeys.EXPIRY_YEAR,
    ADVANTAGE: paramKeys.ADVANTAGE,
    DISADVANTAGE: paramKeys.DISADVANTAGE,
    BONDING_ENVS: paramKeys.BONDING_ENVS,
    SURFACE_MATERIALS: paramKeys.SURFACE_MATERIALS,
    PRINTERS: paramKeys.PRINTERS,
    NOT_SUITABLE_FOR: paramKeys.NOT_SUITABLE_FOR
  }
}
