import Request from '../Request';
import paramKeys from '../paramKeys';

export default class GetAllDashBoardSaleForSalesPeopleRequest extends Request {
    static Keys = {
        DASHBOARD_SALE_CURRENT_MONTH: paramKeys.DASHBOARD_SALE_CURRENT_MONTH,
        DASHBOARD_SALE_CURRENT_YEAR: paramKeys.DASHBOARD_SALE_CURRENT_YEAR,
        DASHBOARD_SALE_REMAINING_DAYS: paramKeys.DASHBOARD_SALE_REMAINING_DAYS,
        DASHBOARD_SALE_TOTAL_REVENUE: paramKeys.DASHBOARD_SALE_TOTAL_REVENUE,
        DASHBOARD_SALE_TOTAL_KPI: paramKeys.DASHBOARD_SALE_TOTAL_KPI,
        DASHBOARD_SALE_PERCENT_KPI: paramKeys.DASHBOARD_SALE_PERCENT_KPI,
        DASHBOARD_SALE_REVENUE_TODAY: paramKeys.DASHBOARD_SALE_REVENUE_TODAY,
        DASHBOARD_SALE_ORDERS_TODAY: paramKeys.DASHBOARD_SALE_ORDERS_TODAY,
        DASHBOARD_SALE_TOTAL_REVENUE_FOR_YEAR: paramKeys.DASHBOARD_SALE_TOTAL_REVENUE_FOR_YEAR,
        DASHBOARD_SALE_TOP_SALESPERSON: paramKeys.DASHBOARD_SALE_TOP_SALESPERSON,
    };
}