import Request from '../Request'
import paramKeys from '../paramKeys'

export default class UpdateProductManagementRequest extends Request {
  static Keys = {
    PRODUCT_DETAIL_ID: paramKeys.PRODUCT_DETAIL_ID,
    PRODUCT_CODE: paramKeys.PRODUCT_CODE,
    PRODUCT_NAME: paramKeys.PRODUCT_NAME,
    SUPPLIER_ID: paramKeys.SUPPLIER_ID,
    SUPPLIER_CODE: paramKeys.SUPPLIER_CODE,
    VN_PRODUCT_CATEGORY_NAME: paramKeys.VN_PRODUCT_CATEGORY_NAME,
    EN_PRODUCT_CATEGORY_NAME: paramKeys.EN_PRODUCT_CATEGORY_NAME,
    PRICE_M2: paramKeys.PRICE_M2,
    PRODUCT_GROUP_ID: paramKeys.PRODUCT_GROUP_ID,
    DESCRIPTION: paramKeys.DESCRIPTION,
    NOTE: paramKeys.NOTE,
    SPECIFICATIONS: paramKeys.SPECIFICATIONS,

    SURFACE_TYPE: paramKeys.SURFACE_TYPE,
    SURFACE_QUANTIFICATION: paramKeys.SURFACE_QUANTIFICATION,
    SURFACE_QUANTIFICATION_TOLERANCE: paramKeys.SURFACE_QUANTIFICATION_TOLERANCE,
    SURFACE_QUANTIFICATION_TOLERANCE_TYPE_ID: paramKeys.SURFACE_QUANTIFICATION_TOLERANCE_TYPE_ID,

    SURFACE_THICKNESS: paramKeys.SURFACE_THICKNESS,
    SURFACE_THICKNESS_TOLERANCE: paramKeys.SURFACE_THICKNESS_TOLERANCE,
    SURFACE_THICKNESS_TOLERANCE_TYPE_ID: paramKeys.SURFACE_THICKNESS_TOLERANCE_TYPE_ID,

    ADHESIVE_TYPE: paramKeys.ADHESIVE_TYPE,
    ADHESIVE_MEASUREMENT: paramKeys.ADHESIVE_MEASUREMENT,
    ADHESIVE_MEASUREMENT_TOLERANCE: paramKeys.ADHESIVE_MEASUREMENT_TOLERANCE,
    ADHESIVE_MEASUREMENT_TOLERANCE_TYPE_ID: paramKeys.ADHESIVE_MEASUREMENT_TOLERANCE_TYPE_ID,

    ADHESIVE_THICKNESS: paramKeys.ADHESIVE_THICKNESS,
    ADHESIVE_THICKNESS_TOLERANCE: paramKeys.ADHESIVE_THICKNESS_TOLERANCE,
    ADHESIVE_THICKNESS_TOLERANCE_TYPE_ID: paramKeys.ADHESIVE_THICKNESS_TOLERANCE_TYPE_ID,

    BASE_TYPE: paramKeys.BASE_TYPE,
    BASE_MEASUREMENT: paramKeys.BASE_MEASUREMENT,
    BASE_MEASUREMENT_TOLERANCE: paramKeys.BASE_MEASUREMENT_TOLERANCE,
    BASE_MEASUREMENT_TOLERANCE_TYPE_ID: paramKeys.BASE_MEASUREMENT_TOLERANCE_TYPE_ID,

    BASE_THICKNESS: paramKeys.BASE_THICKNESS,
    BASE_THICKNESS_TOLERANCE: paramKeys.BASE_THICKNESS_TOLERANCE,
    BASE_THICKNESS_TOLERANCE_TYPE_ID: paramKeys.BASE_THICKNESS_TOLERANCE_TYPE_ID,

    ADHESIVE_FORCE: paramKeys.ADHESIVE_FORCE,
    ADHESIVE_FORCE_TOLERANCE: paramKeys.ADHESIVE_FORCE_TOLERANCE,
    ADHESIVE_FORCE_TOLERANCE_TYPE_ID: paramKeys.ADHESIVE_FORCE_TOLERANCE_TYPE_ID,

    TEMPERATURE_FROM: paramKeys.TEMPERATURE_FROM,
    TEMPERATURE_TO: paramKeys.TEMPERATURE_TO,
    EXPIRY_YEAR: paramKeys.EXPIRY_YEAR,
    ADVANTAGE: paramKeys.ADVANTAGE,
    DISADVANTAGE: paramKeys.DISADVANTAGE,
    BONDING_ENVS: paramKeys.BONDING_ENVS,
    SURFACE_MATERIALS: paramKeys.SURFACE_MATERIALS,
    PRINTERS: paramKeys.PRINTERS,
    NOT_SUITABLE_FOR: paramKeys.NOT_SUITABLE_FOR,
    MIN_INVENTORY: paramKeys.MIN_INVENTORY,
    MAX_INVENTORY: paramKeys.MAX_INVENTORY,
    PDFS: paramKeys.PDFS
  }
}
