const commons = {
  MAX_ADDRESS_COUNT: 5,
  MAX_GOODS_NAME_COUNT: 5,
  STATUS_TOAST_SUCCESS: 'success',
  STATUS_TOAST_ERROR: 'error',
  MAX_CONTACT_COUNT: 5,
  TYPE_DISPLAY_ALL_CUSTOMER: 2,
  OFFICE_ADDRESS: 'officeAddress',
  FACTORY_ADDRESS: 'factoryAddress',
  BRANCH_ADDRESS: 'branchAddress',
  MAX_BRANCH_COUNT: 10,
  FORMAT_IMAGE_FILE: ['jpeg', 'png', 'jpg'],
  FORMAT_VIDEO_FILE: ['mp4', 'webm', 'ogg', 'mov', 'mkv'],
  MAX_SIZE_IMAGE: 5 * 1024 * 1024,
  MAX_SIZE_VIDEO: 100 * 1024 * 1024,
  QUOTATION_HISTORY_ID: 'quotation_history_id',
  DEBT_AGE_ID: 'debt_age_id',
  CLAIM_ID: 'claim_id',
  CALENDAR_ID: 'id',
  FORMAT_FILE: ['pdf'],
  MAX_SIZE_FILE: 5 * 1024 * 1024,
  NUMBER_ONE: 1,
  NUMBER_TWO: 2,
  NUMBER_THREE: 3,
  NUMBER_FOUR: 4,
  NUMBER_TEN: 10,
  GRAMS_PER_SQUARE_METER: 'g/m2',
  MICROMETER: 'mic',
  NEWTONS_PER_25_MILIMETERS: 'N/25mm',
  NUMBER_MAX_LENGTH: 9999999999999,
  INLAND: 1,
  FOREIGN: 2,
  ZERO: 0
}
export default commons
