import Request from '../Request';
import paramKeys from '../paramKeys';

export default class UpdateCustomerHandbookAllRequest extends Request {
    static Keys = {
        HANDBOOK_CUSTOMER_ID: paramKeys.HANDBOOK_CUSTOMER_ID,
        WEBSITE_ADDRESS: paramKeys.WEBSITE_ADDRESS,
        FANPAGE_ADDRESS: paramKeys.FANPAGE_ADDRESS,
        OFFICE_ADDRESS: paramKeys.OFFICE_ADDRESS,
        ENTERPRISE_ESTABLISHMENT_DATE: paramKeys.ENTERPRISE_ESTABLISHMENT_DATE,
        PERSONNEL_SACELE_ID: paramKeys.PERSONNEL_SACELE_ID,
        FACTORY_SCALE_ID: paramKeys.FACTORY_SCALE_ID,
        COMPANY_TYPE_ID: paramKeys.COMPANY_TYPE_ID,
        CUSTOMER_CONTACTS: paramKeys.CUSTOMER_CONTACTS,
        IMAGE_HANDBOOKS: paramKeys.IMAGE_HANDBOOKS,
        PRODUCT_GROUP_IDS: paramKeys.PRODUCT_GROUP_IDS,
        FREQUENCY_PURCHASE_MONTHLY: paramKeys.FREQUENCY_PURCHASE_MONTHLY,
        INDUSTRY_GROUP_ID: paramKeys.INDUSTRY_GROUP_ID,
        REGION: paramKeys.REGION,
        PRODUCT_SUBSTITUTABILITY_ID: paramKeys.PRODUCT_SUBSTITUTABILITY_ID,
        ORDER_PLAN_HANDBOOK_ID: paramKeys.ORDER_PLAN_HANDBOOK_ID,
        QUALITY_REQUIRE_ID: paramKeys.QUALITY_REQUIRE_ID,
        PRODUCT_APPLICATION_ID: paramKeys.PRODUCT_APPLICATION_ID,
        FREQUENCY_COMPANY_VISIT_ID: paramKeys.FREQUENCY_COMPANY_VISIT_ID,
        ENTERPRISE_BIRTHDAY: paramKeys.ENTERPRISE_BIRTHDAY,
        INCENTIVE_POLICY_ID: paramKeys.INCENTIVE_POLICY_ID,
        DISCOUNT_POLICY: paramKeys.DISCOUNT_POLICY,
        PERSONALITY: paramKeys.PERSONALITY,
        SPECIAL_NOTE: paramKeys.SPECIAL_NOTE,
        CONSULTATION_HISTORIES: paramKeys.CONSULTATION_HISTORIES,
        DEVICE_MACHINES: paramKeys.DEVICE_MACHINES,
        ADDRESS_DELIVERIES: paramKeys.ADDRESS_DELIVERIES,
    };
}
